### ISSUE TITLE
Is there a design flaw in the update function?

### ISSUE THREAD

**Issue by Beosin20180329** [wombat-exchange/v1-core#3]
Hello, we are the Beosin security team. Is there any design flaw in the update function of your VeWom contract? you can look at.
As shown in the figure below, when the user updates the lockdays, the current timestamp shall prevail. Is this in line with the design? For example: the user deposits 100Wom to lock for 10 days, and obtains 10 veWons (1 veWon per day); after the 8th day, the user calls update to update the lockDays to 12 days (the function requires that the new lockDays cannot be lower than the original lockDays), then This part of Wom will be locked for 20 days, but the rewards are only 12 veWon(8+(12-8)).
![image](https://user-images.githubusercontent.com/58016160/230328461-e4f7fc7e-d5f2-43e5-8104-167932fa5459.png)

**Comment by jack-wombat** [comment]
This is by design.
